apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-trby
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-trby
    app.kubernetes.io/part-of: ci1t-43256-0010-app
  name: devfile-sample-trby
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-trby
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-trby
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0010-tenant/ci1t-43256-0010-app/devfile-sample-trby@sha256:cb1d36a69aa5a892a69ac7d4192a3d92caf42db0da774d9350dda3153bbc5e61
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
